version: '3.7'
services:
   web:
      image: nginx:latest
      networks:
         - app_net
      restart: unless-stopped
      ports:
         - "80:80"
         - "443:443"
      volumes:
         # Application
         - ./_host-volumes/app/:/opt/app/:delegated
         # upload directory
         - ./_host-volumes/app/web/uploads/:/opt/app/web/uploads/:rw
         # Certificates and other configurations
         - ./php/etc/nginx/conf.d/:/etc/nginx/conf.d/
         - ./php/etc/nginx/certs/:/etc/nginx/certs/:delegated
         # Nginx Logs
         - ./_host-volumes/logs/:/var/log/nginx/
   php:
      build: 
         dockerfile: Dockerfile-debian
         context: 'php'
      image: yiiframework/php:7.4-fpm
      networks:
         - app_net
      restart: unless-stopped
      links:
         - mariadb
         - web:videos.dev
      volumes:
         - ./tests:/tests:delegated
         # Application
         - ./_host-volumes/app/:/opt/app/:delegated
         # Composer cache
         - /home/abel/.composer-docker/cache:/root/.composer/cache:delegated
         # supervisor log
         - ./_host-volumes/logs/:/var/log/supervisor/
   mariadb:
      build:
         context: db
         dockerfile: Dockerfile
      image: mariadb:latest
      expose:
         - 3306
      ports:
         - 3306:3306
      restart: unless-stopped
      networks:
         - app_net
      environment:
         - MYSQL_ROOT_PASSWORD=senhadoroot
         - MYSQL_DATABASE=ufrgsvideos
         - MYSQL_USER=ufrgsvideos
         - MYSQL_PASSWORD=ufrgsvideos
      volumes:
         - ./_host-volumes/db/init:/docker-entrypoint-initdb.d
         - ./_host-volumes/db/data:/var/lib/mysql
   cache:
      image: redis
      restart: unless-stopped
      networks:
         - app_net

networks:
   app_net:
      driver: bridge

