FROM mariadb:latest

# ADD resources/my.cnf /etc/mysql/my.cnf
# RUN echo "character-set-server=utf8" >> /etc/mysql/conf.d/mysql.cnf \
RUN echo "innodb_large_prefix=ON" >> /etc/mysql/conf.d/docker.cnf
